# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Comment Backend Coverage Report

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: server/

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: server/
    - name: Install dependencies
      run: |
        pip install -U pip pytest-cov
        pip install -r requirements.txt
    - name: Build coverage file
      run: |
        pytest --cov=app test > pytest-coverage.txt
      env:
        JWT_SECRET_KEY: $GITHUB_SHA
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2